# Generated by Django 6.0.2 on 2026-03-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requestpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
