# Generated by Django 6.0.2 on 2026-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='slug',
            field=models.SlugField(default='kareem'),
        ),
    ]
