# Generated by Django 6.0.2 on 2026-03-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_owner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
