# Generated by Django 6.0.2 on 2026-03-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_owner_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='slug',
        ),
    ]
